//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto02_EduardoR_BryanS.wcfPago2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Pago", Namespace="http://schemas.datacontract.org/2004/07/wcfPago1")]
    [System.SerializableAttribute()]
    public partial class tbl_Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double adicionalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double bancarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int creditos1raField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int creditos2daField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int creditos3raField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double factorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double feponField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double recargoRep2daField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double recargoRep3raField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valorApagarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valorArancelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valorMatriculaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double adicionales {
            get {
                return this.adicionalesField;
            }
            set {
                if ((this.adicionalesField.Equals(value) != true)) {
                    this.adicionalesField = value;
                    this.RaisePropertyChanged("adicionales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double bancario {
            get {
                return this.bancarioField;
            }
            set {
                if ((this.bancarioField.Equals(value) != true)) {
                    this.bancarioField = value;
                    this.RaisePropertyChanged("bancario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditos1ra {
            get {
                return this.creditos1raField;
            }
            set {
                if ((this.creditos1raField.Equals(value) != true)) {
                    this.creditos1raField = value;
                    this.RaisePropertyChanged("creditos1ra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditos2da {
            get {
                return this.creditos2daField;
            }
            set {
                if ((this.creditos2daField.Equals(value) != true)) {
                    this.creditos2daField = value;
                    this.RaisePropertyChanged("creditos2da");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int creditos3ra {
            get {
                return this.creditos3raField;
            }
            set {
                if ((this.creditos3raField.Equals(value) != true)) {
                    this.creditos3raField = value;
                    this.RaisePropertyChanged("creditos3ra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double factor {
            get {
                return this.factorField;
            }
            set {
                if ((this.factorField.Equals(value) != true)) {
                    this.factorField = value;
                    this.RaisePropertyChanged("factor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double fepon {
            get {
                return this.feponField;
            }
            set {
                if ((this.feponField.Equals(value) != true)) {
                    this.feponField = value;
                    this.RaisePropertyChanged("fepon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPago {
            get {
                return this.idPagoField;
            }
            set {
                if ((this.idPagoField.Equals(value) != true)) {
                    this.idPagoField = value;
                    this.RaisePropertyChanged("idPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double recargoRep2da {
            get {
                return this.recargoRep2daField;
            }
            set {
                if ((this.recargoRep2daField.Equals(value) != true)) {
                    this.recargoRep2daField = value;
                    this.RaisePropertyChanged("recargoRep2da");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double recargoRep3ra {
            get {
                return this.recargoRep3raField;
            }
            set {
                if ((this.recargoRep3raField.Equals(value) != true)) {
                    this.recargoRep3raField = value;
                    this.RaisePropertyChanged("recargoRep3ra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorApagar {
            get {
                return this.valorApagarField;
            }
            set {
                if ((this.valorApagarField.Equals(value) != true)) {
                    this.valorApagarField = value;
                    this.RaisePropertyChanged("valorApagar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorArancel {
            get {
                return this.valorArancelField;
            }
            set {
                if ((this.valorArancelField.Equals(value) != true)) {
                    this.valorArancelField = value;
                    this.RaisePropertyChanged("valorArancel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valorMatricula {
            get {
                return this.valorMatriculaField;
            }
            set {
                if ((this.valorMatriculaField.Equals(value) != true)) {
                    this.valorMatriculaField = value;
                    this.RaisePropertyChanged("valorMatricula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Usuario", Namespace="http://schemas.datacontract.org/2004/07/wcfPago1")]
    [System.SerializableAttribute()]
    public partial class tbl_Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido1UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellido2UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre1UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre2UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroCedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quintilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido1Usuario {
            get {
                return this.apellido1UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido1UsuarioField, value) != true)) {
                    this.apellido1UsuarioField = value;
                    this.RaisePropertyChanged("apellido1Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido2Usuario {
            get {
                return this.apellido2UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.apellido2UsuarioField, value) != true)) {
                    this.apellido2UsuarioField = value;
                    this.RaisePropertyChanged("apellido2Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre1Usuario {
            get {
                return this.nombre1UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre1UsuarioField, value) != true)) {
                    this.nombre1UsuarioField = value;
                    this.RaisePropertyChanged("nombre1Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre2Usuario {
            get {
                return this.nombre2UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre2UsuarioField, value) != true)) {
                    this.nombre2UsuarioField = value;
                    this.RaisePropertyChanged("nombre2Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroCedula {
            get {
                return this.numeroCedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroCedulaField, value) != true)) {
                    this.numeroCedulaField = value;
                    this.RaisePropertyChanged("numeroCedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quintil {
            get {
                return this.quintilField;
            }
            set {
                if ((this.quintilField.Equals(value) != true)) {
                    this.quintilField = value;
                    this.RaisePropertyChanged("quintil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="quintilx", Namespace="http://schemas.datacontract.org/2004/07/wcfPago1")]
    [System.SerializableAttribute()]
    public partial class quintilx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double arancelesTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double factorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double matriculaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double arancelesTotal {
            get {
                return this.arancelesTotalField;
            }
            set {
                if ((this.arancelesTotalField.Equals(value) != true)) {
                    this.arancelesTotalField = value;
                    this.RaisePropertyChanged("arancelesTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double factor {
            get {
                return this.factorField;
            }
            set {
                if ((this.factorField.Equals(value) != true)) {
                    this.factorField = value;
                    this.RaisePropertyChanged("factor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double matricula {
            get {
                return this.matriculaField;
            }
            set {
                if ((this.matriculaField.Equals(value) != true)) {
                    this.matriculaField = value;
                    this.RaisePropertyChanged("matricula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfPago2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPago", ReplyAction="http://tempuri.org/IService1/obtenerPagoResponse")]
        proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago obtenerPago(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPago", ReplyAction="http://tempuri.org/IService1/obtenerPagoResponse")]
        System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago> obtenerPagoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPago2", ReplyAction="http://tempuri.org/IService1/obtenerPago2Response")]
        proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago obtenerPago2(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPago2", ReplyAction="http://tempuri.org/IService1/obtenerPago2Response")]
        System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago> obtenerPago2Async(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPersona", ReplyAction="http://tempuri.org/IService1/obtenerPersonaResponse")]
        proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario obtenerPersona(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPersona", ReplyAction="http://tempuri.org/IService1/obtenerPersonaResponse")]
        System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario> obtenerPersonaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPersonaConCI", ReplyAction="http://tempuri.org/IService1/obtenerPersonaConCIResponse")]
        proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario obtenerPersonaConCI(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPersonaConCI", ReplyAction="http://tempuri.org/IService1/obtenerPersonaConCIResponse")]
        System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario> obtenerPersonaConCIAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerArancel", ReplyAction="http://tempuri.org/IService1/obtenerArancelResponse")]
        proyecto02_EduardoR_BryanS.wcfPago2.quintilx obtenerArancel(int quintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerArancel", ReplyAction="http://tempuri.org/IService1/obtenerArancelResponse")]
        System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.quintilx> obtenerArancelAsync(int quintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerAranceles", ReplyAction="http://tempuri.org/IService1/obtenerArancelesResponse")]
        double obtenerAranceles(int personaQuintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerAranceles", ReplyAction="http://tempuri.org/IService1/obtenerArancelesResponse")]
        System.Threading.Tasks.Task<double> obtenerArancelesAsync(int personaQuintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerMatricula", ReplyAction="http://tempuri.org/IService1/obtenerMatriculaResponse")]
        double obtenerMatricula(int personaQuintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerMatricula", ReplyAction="http://tempuri.org/IService1/obtenerMatriculaResponse")]
        System.Threading.Tasks.Task<double> obtenerMatriculaAsync(int personaQuintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerFactor", ReplyAction="http://tempuri.org/IService1/obtenerFactorResponse")]
        double obtenerFactor(int personaQuintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerFactor", ReplyAction="http://tempuri.org/IService1/obtenerFactorResponse")]
        System.Threading.Tasks.Task<double> obtenerFactorAsync(int personaQuintil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearPago", ReplyAction="http://tempuri.org/IService1/crearPagoResponse")]
        bool crearPago(int creditos1ra, int creditos2da, int creditos3ra, double factor, double valorMatricula, double valorArancel, double recargoRep2da, double recargaRep3ra, double fepon, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearPago", ReplyAction="http://tempuri.org/IService1/crearPagoResponse")]
        System.Threading.Tasks.Task<bool> crearPagoAsync(int creditos1ra, int creditos2da, int creditos3ra, double factor, double valorMatricula, double valorArancel, double recargoRep2da, double recargaRep3ra, double fepon, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : proyecto02_EduardoR_BryanS.wcfPago2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<proyecto02_EduardoR_BryanS.wcfPago2.IService1>, proyecto02_EduardoR_BryanS.wcfPago2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago obtenerPago(int id) {
            return base.Channel.obtenerPago(id);
        }
        
        public System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago> obtenerPagoAsync(int id) {
            return base.Channel.obtenerPagoAsync(id);
        }
        
        public proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago obtenerPago2(int id) {
            return base.Channel.obtenerPago2(id);
        }
        
        public System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Pago> obtenerPago2Async(int id) {
            return base.Channel.obtenerPago2Async(id);
        }
        
        public proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario obtenerPersona(string cedula) {
            return base.Channel.obtenerPersona(cedula);
        }
        
        public System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario> obtenerPersonaAsync(string cedula) {
            return base.Channel.obtenerPersonaAsync(cedula);
        }
        
        public proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario obtenerPersonaConCI(int id) {
            return base.Channel.obtenerPersonaConCI(id);
        }
        
        public System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.tbl_Usuario> obtenerPersonaConCIAsync(int id) {
            return base.Channel.obtenerPersonaConCIAsync(id);
        }
        
        public proyecto02_EduardoR_BryanS.wcfPago2.quintilx obtenerArancel(int quintil) {
            return base.Channel.obtenerArancel(quintil);
        }
        
        public System.Threading.Tasks.Task<proyecto02_EduardoR_BryanS.wcfPago2.quintilx> obtenerArancelAsync(int quintil) {
            return base.Channel.obtenerArancelAsync(quintil);
        }
        
        public double obtenerAranceles(int personaQuintil) {
            return base.Channel.obtenerAranceles(personaQuintil);
        }
        
        public System.Threading.Tasks.Task<double> obtenerArancelesAsync(int personaQuintil) {
            return base.Channel.obtenerArancelesAsync(personaQuintil);
        }
        
        public double obtenerMatricula(int personaQuintil) {
            return base.Channel.obtenerMatricula(personaQuintil);
        }
        
        public System.Threading.Tasks.Task<double> obtenerMatriculaAsync(int personaQuintil) {
            return base.Channel.obtenerMatriculaAsync(personaQuintil);
        }
        
        public double obtenerFactor(int personaQuintil) {
            return base.Channel.obtenerFactor(personaQuintil);
        }
        
        public System.Threading.Tasks.Task<double> obtenerFactorAsync(int personaQuintil) {
            return base.Channel.obtenerFactorAsync(personaQuintil);
        }
        
        public bool crearPago(int creditos1ra, int creditos2da, int creditos3ra, double factor, double valorMatricula, double valorArancel, double recargoRep2da, double recargaRep3ra, double fepon, int id) {
            return base.Channel.crearPago(creditos1ra, creditos2da, creditos3ra, factor, valorMatricula, valorArancel, recargoRep2da, recargaRep3ra, fepon, id);
        }
        
        public System.Threading.Tasks.Task<bool> crearPagoAsync(int creditos1ra, int creditos2da, int creditos3ra, double factor, double valorMatricula, double valorArancel, double recargoRep2da, double recargaRep3ra, double fepon, int id) {
            return base.Channel.crearPagoAsync(creditos1ra, creditos2da, creditos3ra, factor, valorMatricula, valorArancel, recargoRep2da, recargaRep3ra, fepon, id);
        }
    }
}
